version: '3.7'
services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: tms-finder/mongo:latest
    container_name: tms-finder-mongo
    # ports:
    #   - '27017:27017'
    # volumes:
    #   - ../volumes/mongodb/data:/data/db # 指定容器外部的数据存储位置
    # logging:
    #   driver: none

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: tms-finder/back:latest
    container_name: tms-finder-back
    # ports:
    #   - '3000:3000'
    environment:
      - NODE_ENV=production
      # - TMS_KOA_PORT=3000
      - TMS_FINDER_MONGODB_HOST=mongodb
      - TMS_FINDER_MONGODB_PORT=27017
      - TMS_FINDER_FS_ROOTDIR=/home/storage
      # - TMS_FINDER_FS_MONGODB_SOURCE=master
      # - TMS_FINDER_FS_MONGODB_DATABASE=upload
      # - TMS_FINDER_FS_MONGODB_COLLECTION=files
    # volumes:
    #   - ../volumes/files:/home/storage # 指定文件服务的外部存储位置（rootDir）
    command:
      ['./wait_for.sh', 'mongodb:27017', '-t', '300', '--', 'node', 'server']

  ue:
    build:
      context: ../packages/ue
      args:
        vue_app_base_url: /finder_ue
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
        vue_app_support_multi_view: 'No'
        vue_app_support_set_info: 'No'
        # vue_app_auth_server: http://localhost:3000
        # vue_app_api_server: http://localhost:3000
        # vue_app_fs_server: http://localhost:3000
    image: tms-finder/ue:latest
    container_name: tms-finder-ue
    environment:
      - NGINX_WEB_BASE_URL=/finder_ue
      - NGINX_ACCESS_CONTROL_ALLOW_ORIGIN=* # 允许跨域访问
    # ports:
    #   - '8080:80'

  ue_any:
    build:
      context: ./ue_any
      args:
        vue_app_base_url: /finder_ue_any
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
    image: tms-finder/ue_any:latest
    container_name: tms-finder-ue_any
    environment:
      - NGINX_WEB_BASE_URL=/finder_ue_any
    # ports:
    #   - '8081:80'
