# 为插件开发提供的基础镜像 

FROM jasony62/tfd-aio:latest

# 为了后续安装扩展插件做准备。需要增加120M左右。
## 基础工具
RUN npm install -g pnpm typescript
## 解决sharp依赖的libvips包下载慢的问题
COPY ../docker/back/npmlibs/_libvips/libvips-8.12.2-linuxmusl-x64.tar.br /root/.npm/_libvips/libvips-8.12.2-linuxmusl-x64.tar.br

ENTRYPOINT ["start_all.sh"]