version: '3.7'
services:
  mongodb:
    volumes:
      - ../volumes/mongodb/data:/data/db
    ports:
      - '27027:27017'
    # logging:
    # driver: 'none'

  back:
    ports:
      - '3000:3000'
    environment:
      # - TMS_KOA_PORT=3000
      - TMS_FINDER_MONGODB_HOST=mongodb
      - TMS_FINDER_MONGODB_PORT=27017
      - TMS_FINDER_FS_ROOTDIR=/home/storage
    volumes:
      - ../volumes/files:/home/storage # 指定文件服务的外部存储位置（rootDir）
      # - ../back/config/app.local.js:/home/node/app/config/app.local.js # 指定本地配置文件

  ue:
    build:
      args:
        vue_app_auth_server: http://localhost:3000
        vue_app_api_server: http://localhost:3000
        vue_app_fs_server: http://localhost:3000
    ports:
      - '8080:80'
