# 为插件开发提供的基础镜像 
FROM jasony62/tfd-aio:latest

# 修改npm源
RUN npm config set registry https://registry.npmmirror.com

# 为了后续安装扩展插件做准备。需要增加120M左右。
## 基础工具
RUN npm install --location=global pnpm typescript
## 安装sharp包需要的工具
# RUN apk add python3 make
## 解决sharp依赖的libvips包下载慢的问题
# COPY ../docker/back/npmlibs/_libvips/libvips-8.13.3-linuxmusl-x64.tar.br /root/.npm/_libvips/libvips-8.13.3-linuxmusl-x64.tar.br
